<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StudentManagementApi.Domain\StudentManagementApi.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Ardalis.Result" />
    <PackageReference Include="Ardalis.Result.FluentValidation" />
    <PackageReference Include="Ardalis.Specification" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
